export const GAME_CONFIG = {
  title: '除灵实习生 Phase 0',
  baseSalary: 100000,
  escapeTime: 45,
  staminaMax: 100,
  staminaDrainPerSecond: 18,
  staminaRegenPerSecond: 10,
  staminaMinToSprint: 8,
  jumpStaminaCost: 8,
  walkSpeed: 2.6,
  sprintSpeed: 6.0,
  throwCooldown: 0.35,
  interactRadius: 2.2,
  pickupRadius: 2.0,
  whipStaminaCost: 18,
  whipRange: 3.8,
  whipCone: 0.5,
  whipCooldown: 0.45,
  whipComboWindow: 3.5,
  whipRageBase: 5,
  whipKnockback: 7,
  whipSpinDuration: 0.55,
  maxLockerHides: 2,
  noiseRunRadius: 14,
  noiseThrowRadius: 12,
  noiseBreakRadius: 16,
  quietDecay: 1.5,
  hideDecay: 6,
  slapCooldown: 2.5,
  batteryDrainPerSecond: 0.6,
  batteryDrainPerClue: 8,
  phoneOpenDrainPerSecond: 4.5
};
